# Generated by Django 4.2.3 on 2023-09-26 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('numero_cliente', models.CharField(max_length=20)),
                ('historial_pedidos', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquipoTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField()),
                ('fecha_entrega_deseada', models.DateField()),
                ('estado_pedido', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPrincipal.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('contacto_principal', models.CharField(max_length=100)),
                ('servicios_proporcionados', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicioTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('parametros_tratamiento', models.TextField()),
                ('equipo_requerido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_finalizacion', models.DateTimeField()),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tiempo_tratamiento', models.DurationField()),
                ('resultados', models.TextField()),
                ('pedido_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPrincipal.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultados_pruebas', models.TextField()),
                ('responsable_prueba', models.CharField(max_length=100)),
                ('pedido_o_tratamiento_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPrincipal.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_programada', models.DateTimeField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPrincipal.pedido')),
                ('proveedor_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPrincipal.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='servicios_solicitados',
            field=models.ManyToManyField(to='AppPrincipal.serviciotratamiento'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('factura_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPrincipal.factura')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='pedido_asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPrincipal.pedido'),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('fecha_contratacion', models.DateField()),
                ('historial_empleo', models.TextField()),
                ('capacitaciones', models.ManyToManyField(to='AppPrincipal.capacitacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('asociado_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPrincipal.pedido')),
            ],
        ),
    ]
