# Generated by Django 4.2.3 on 2023-10-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrincipal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacitacion',
            options={'verbose_name': 'Capacitacion', 'verbose_name_plural': 'Capacitaciones'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ('nombre',), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='programacion',
            options={'verbose_name': 'Programacion', 'verbose_name_plural': 'Programaciones'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='registrocalidad',
            options={'verbose_name': 'Registro de Calidad', 'verbose_name_plural': 'Registros de Calidad'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_cliente',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='registrotratamiento',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('numero_cliente', 'correo_electronico')},
        ),
    ]
